# Pandas em poucos minutos

---

### Instalação e importação

In [ ]:
import pandas as pd
from google.colab import files

ModuleNotFoundError: No module named 'google'

:

### DataFrames e Series

In [2]:
dados = {
    "Nome": ["Ana", "Bruno", "Carlos"],
    "Idade": [25, 47, 32],
}
df = pd.DataFrame(dados)
df

     Nome  Idade
0     Ana     25
1   Bruno     47
2  Carlos     32

### Lendo tabelas

In [3]:

# Vai abrir uma janela para selecionar o arquivo no seu computador
uploaded = files.upload()

df = pd.read_csv("funcionarios.csv", sep=",")  # troque o separador se necessário

NameError: name 'files' is not defined

### Manipulação básica de dados

In [5]:
df.head()

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4

In [6]:
df.tail()

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

In [7]:
df[['Nome', 'Idade']] #Me aparecerão apenas as colunas "Nome" e "Idade"

                         Nome  Idade
0    Sra. Isabela Vasconcelos     44
1             Heitor Teixeira     40
2          Bianca Vasconcelos     44
3               Alice Machado     40
4           Antônio Fernandes     54
5       Henry Gabriel da Mata     42
6   Sra. Maria Luiza Oliveira     58
7                Isis Marques     24
8           Sr. Vitor da Rosa     61
9                Théo Cardoso     54
10          Marcelo Rodrigues     57
11         Maria Clara Santos     39
12                 Sofia Rios     45
13          Benicio das Neves     22
14              Levi Silveira     42
15     Maria Fernanda Rezende     29
16         Thomas Casa Grande     33
17        Davi Miguel Ribeiro     48
18     Dr. Mathias Montenegro     20
19           Samuel Gonçalves     21

In [8]:
df['Idade']

0     44
1     40
2     44
3     40
4     54
5     42
6     58
7     24
8     61
9     54
10    57
11    39
12    45
13    22
14    42
15    29
16    33
17    48
18    20
19    21
Name: Idade, dtype: int64

In [9]:
df[df['Idade'] > 30]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5

In [10]:
df[df['Salário'] > 5000]

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4

### Combinando filtros

In [11]:
#Vamos separar os que ganham muito porém com pouca idade
df_filtrado = df[(df["Idade"] < 30) & (df["Salário"] > 5000)]
df_filtrado

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4

### Criando e removendo colunas

In [12]:
df['Salário Anual'] = df['Salário'] * 12
df

,ID,Nome,Idade,Data de Registro,Salário,Ativo,ID Departamento,Salário Anual
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4,53221.56
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2,94019.64
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2,37134.60
3,4,Alice Machado,40,2023-10-10,6287.20,True,2,75446.40
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4,85661.16
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4,59299.44
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5,85335.00
7,8,Isis Marques,24,2023-02-05,8438.66,True,1,101263.92
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1,28366.20
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2,96355.80
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1,97312.20
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4,31220.16
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1,59880.12
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5,30498.48
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5,111143.76
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3,89234.52
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2,98470.80
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5,31500.12
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4,114801.96
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3,46619.88

In [14]:
# axis=0 significa linhas, axis=1 significa colunas.
# Como queremos excluir a coluna "Salário", usamos axis=1.
df = df.drop('Salário', axis=1)

KeyError: "['Salário'] not found in axis"

### Resumindo dados

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                20 non-null     int64
 1   Nome              20 non-null     object
 2   Idade             20 non-null     int64
 3   Data de Registro  20 non-null     object
 4   Ativo             20 non-null     bool
 5   ID Departamento   20 non-null     int64
 6   Salário Anual     20 non-null     float64
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 1.1+ KB

In [16]:
df.describe()

             ID      Idade  ID Departamento  Salário Anual
count  20.00000  20.000000        20.000000      20.000000
mean   10.50000  40.850000         3.000000   71339.286000
std     5.91608  12.716649         1.486784   29695.663727
min     1.00000  20.000000         1.000000   28366.200000
25%     5.75000  32.000000         2.000000   44248.560000
50%    10.50000  42.000000         3.000000   80390.700000
75%    15.25000  49.500000         4.000000   96594.900000
max    20.00000  61.000000         5.000000  114801.960000

In [17]:
df['Salário Anual'].sum()

np.float64(1426785.72)

In [18]:
df['Salário Anual'].mean()

np.float64(71339.286)

### Contando ocorrências

In [19]:
#Vamos chegar quem está ativo e quem se desligou da empresa
df['Ativo'].value_counts()

Ativo
True     11
False     9
Name: count, dtype: int64

In [20]:
df['ID Departamento'].value_counts()

ID Departamento
4    5
2    5
5    4
1    4
3    2
Name: count, dtype: int64

### Operações de agregação

In [21]:
df.groupby('ID Departamento')['Salário Anual'].mean()

ID Departamento
1    71705.610
2    80285.448
3    67927.200
4    68840.856
5    64619.340
Name: Salário Anual, dtype: float64

In [22]:
df.groupby('ID Departamento')['Salário Anual'].sum()

ID Departamento
1    286822.44
2    401427.24
3    135854.40
4    344204.28
5    258477.36
Name: Salário Anual, dtype: float64

In [23]:
df.groupby('ID Departamento')['Salário Anual'].max()

ID Departamento
1    101263.92
2     98470.80
3     89234.52
4    114801.96
5    111143.76
Name: Salário Anual, dtype: float64

### Ordenando dados

In [24]:
df.sort_values(by='Salário Anual')

,ID,Nome,Idade,Data de Registro,Ativo,ID Departamento,Salário Anual
8,9,Sr. Vitor da Rosa,61,2024-03-25,False,1,28366.20
13,14,Benicio das Neves,22,2022-04-15,True,5,30498.48
11,12,Maria Clara Santos,39,2023-10-21,True,4,31220.16
17,18,Davi Miguel Ribeiro,48,2022-07-10,False,5,31500.12
2,3,Bianca Vasconcelos,44,2022-10-28,False,2,37134.60
19,20,Samuel Gonçalves,21,2023-10-03,True,3,46619.88
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,True,4,53221.56
5,6,Henry Gabriel da Mata,42,2024-01-26,False,4,59299.44
12,13,Sofia Rios,45,2023-05-19,False,1,59880.12
3,4,Alice Machado,40,2023-10-10,True,2,75446.40
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,True,5,85335.00
4,5,Antônio Fernandes,54,2023-08-09,True,4,85661.16
15,16,Maria Fernanda Rezende,29,2023-11-18,False,3,89234.52
1,2,Heitor Teixeira,40,2022-01-17,False,2,94019.64
9,10,Théo Cardoso,54,2022-09-05,True,2,96355.80
10,11,Marcelo Rodrigues,57,2024-02-06,True,1,97312.20
16,17,Thomas Casa Grande,33,2024-03-29,False,2,98470.80
7,8,Isis Marques,24,2023-02-05,True,1,101263.92
14,15,Levi Silveira,42,2024-02-10,True,5,111143.76
18,19,Dr. Mathias Montenegro,20,2023-08-17,False,4,114801.96

In [25]:
# Ordenar o DataFrame df pela coluna "Salário Anual"
# O parâmetro by='Salário Anual' indica a coluna usada para a ordenação
# O parâmetro ascending=False significa ordem decrescente (do maior para o menor)
# inplace=True faz a ordenação ser aplicada diretamente no df, sem precisar criar uma cópia
df.sort_values(by="Salário Anual", ascending=False, inplace=True)

# Mostrar o DataFrame já ordenado
df

,ID,Nome,Idade,Data de Registro,Ativo,ID Departamento,Salário Anual
18,19,Dr. Mathias Montenegro,20,2023-08-17,False,4,114801.96
14,15,Levi Silveira,42,2024-02-10,True,5,111143.76
7,8,Isis Marques,24,2023-02-05,True,1,101263.92
16,17,Thomas Casa Grande,33,2024-03-29,False,2,98470.80
10,11,Marcelo Rodrigues,57,2024-02-06,True,1,97312.20
9,10,Théo Cardoso,54,2022-09-05,True,2,96355.80
1,2,Heitor Teixeira,40,2022-01-17,False,2,94019.64
15,16,Maria Fernanda Rezende,29,2023-11-18,False,3,89234.52
4,5,Antônio Fernandes,54,2023-08-09,True,4,85661.16
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,True,5,85335.00
3,4,Alice Machado,40,2023-10-10,True,2,75446.40
12,13,Sofia Rios,45,2023-05-19,False,1,59880.12
5,6,Henry Gabriel da Mata,42,2024-01-26,False,4,59299.44
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,True,4,53221.56
19,20,Samuel Gonçalves,21,2023-10-03,True,3,46619.88
2,3,Bianca Vasconcelos,44,2022-10-28,False,2,37134.60
17,18,Davi Miguel Ribeiro,48,2022-07-10,False,5,31500.12
11,12,Maria Clara Santos,39,2023-10-21,True,4,31220.16
13,14,Benicio das Neves,22,2022-04-15,True,5,30498.48
8,9,Sr. Vitor da Rosa,61,2024-03-25,False,1,28366.20

### Combinando dados

In [26]:
uploaded = files.upload()
df_dept = pd.read_csv('departamentos.csv')
df_dept

Saving departamentos.csv to departamentos.csv

   ID Departamento Nome Departamento
0                1            Vendas
1                2                TI
2                3                RH
3                4        Financeiro
4                5         Marketing

In [27]:
#Vamos juntar os dois
df_final = pd.merge(df, df_dept)
df_final

,ID,Nome,Idade,Data de Registro,Ativo,ID Departamento,Salário Anual,Nome Departamento
0,19,Dr. Mathias Montenegro,20,2023-08-17,False,4,114801.96,Financeiro
1,15,Levi Silveira,42,2024-02-10,True,5,111143.76,Marketing
2,8,Isis Marques,24,2023-02-05,True,1,101263.92,Vendas
3,17,Thomas Casa Grande,33,2024-03-29,False,2,98470.80,TI
4,11,Marcelo Rodrigues,57,2024-02-06,True,1,97312.20,Vendas
5,10,Théo Cardoso,54,2022-09-05,True,2,96355.80,TI
6,2,Heitor Teixeira,40,2022-01-17,False,2,94019.64,TI
7,16,Maria Fernanda Rezende,29,2023-11-18,False,3,89234.52,RH
8,5,Antônio Fernandes,54,2023-08-09,True,4,85661.16,Financeiro
9,7,Sra. Maria Luiza Oliveira,58,2024-08-24,True,5,85335.00,Marketing
10,4,Alice Machado,40,2023-10-10,True,2,75446.40,TI
11,13,Sofia Rios,45,2023-05-19,False,1,59880.12,Vendas
12,6,Henry Gabriel da Mata,42,2024-01-26,False,4,59299.44,Financeiro
13,1,Sra. Isabela Vasconcelos,44,2022-02-11,True,4,53221.56,Financeiro
14,20,Samuel Gonçalves,21,2023-10-03,True,3,46619.88,RH
15,3,Bianca Vasconcelos,44,2022-10-28,False,2,37134.60,TI
16,18,Davi Miguel Ribeiro,48,2022-07-10,False,5,31500.12,Marketing
17,12,Maria Clara Santos,39,2023-10-21,True,4,31220.16,Financeiro
18,14,Benicio das Neves,22,2022-04-15,True,5,30498.48,Marketing
19,9,Sr. Vitor da Rosa,61,2024-03-25,False,1,28366.20,Vendas

In [28]:
# Arredondar os salários anuais para 2 casas decimais
df_final["Salário Anual"] = df_final["Salário Anual"].round(2)

# Remover a coluna ID Departamento
df_final.drop("ID Departamento", axis=1, inplace=True)

# Ordenar do maior para o menor salário anual
df_final.sort_values(by="Salário Anual", ascending=False, inplace=True)

# Mostrar o resultado final
df_final

,ID,Nome,Idade,Data de Registro,Ativo,Salário Anual,Nome Departamento
0,19,Dr. Mathias Montenegro,20,2023-08-17,False,114801.96,Financeiro
1,15,Levi Silveira,42,2024-02-10,True,111143.76,Marketing
2,8,Isis Marques,24,2023-02-05,True,101263.92,Vendas
3,17,Thomas Casa Grande,33,2024-03-29,False,98470.80,TI
4,11,Marcelo Rodrigues,57,2024-02-06,True,97312.20,Vendas
5,10,Théo Cardoso,54,2022-09-05,True,96355.80,TI
6,2,Heitor Teixeira,40,2022-01-17,False,94019.64,TI
7,16,Maria Fernanda Rezende,29,2023-11-18,False,89234.52,RH
8,5,Antônio Fernandes,54,2023-08-09,True,85661.16,Financeiro
9,7,Sra. Maria Luiza Oliveira,58,2024-08-24,True,85335.00,Marketing
10,4,Alice Machado,40,2023-10-10,True,75446.40,TI
11,13,Sofia Rios,45,2023-05-19,False,59880.12,Vendas
12,6,Henry Gabriel da Mata,42,2024-01-26,False,59299.44,Financeiro
13,1,Sra. Isabela Vasconcelos,44,2022-02-11,True,53221.56,Financeiro
14,20,Samuel Gonçalves,21,2023-10-03,True,46619.88,RH
15,3,Bianca Vasconcelos,44,2022-10-28,False,37134.60,TI
16,18,Davi Miguel Ribeiro,48,2022-07-10,False,31500.12,Marketing
17,12,Maria Clara Santos,39,2023-10-21,True,31220.16,Financeiro
18,14,Benicio das Neves,22,2022-04-15,True,30498.48,Marketing
19,9,Sr. Vitor da Rosa,61,2024-03-25,False,28366.20,Vendas

### Escrevendo dados em arquivos

In [ ]:
df_final.to_csv("df_final.csv", sep=";", decimal=",", index=False, encoding="utf-8-sig")


# Faz o download para o seu computador
files.download("df_final.csv")