
# 📊 Manipulação de Tabelas com Pandas

## 📌 Objetivo
Este notebook ensinará comandos básicos para manipulação de tabelas usando **Pandas**.
O objetivo é aprender operações essenciais como:

- Visualizar estatísticas básicas
- Renomear colunas
- Selecionar colunas e linhas
- Remover dados indesejados

## 📊 Manipulando dados

- Após obter uma boa fonte de dados você certamente precisará realizar algumas limpezas e manipulações para que os dados estejam no ponto ideal para as fases finais de uma análise: execução de modelos econométricos, visualizações de dados, tabelas agregadas, relatórios etc.

- A realidade é que, na prática, os dados nunca estarão do jeito que você de fato precisa. Portanto, é fundamental dominar técnicas de manipulação de dados.

- Entendamos a manipulação de dados como o ato de transformar, reestruturar, limpar, agregar e juntar os dados.

- Para se ter uma noção da importância dessa fase, alguns estudiosos da área de Ciência de Dados costumam afirmar que 80% do trabalho é encontrar uma boa fonte de dados, limpar e preparar os dados, sendo que os 20% restantes seriam o trabalho de aplicar modelos e realizar alguma análise propriamente dita.


## 📂 O Dataset: Penguins

Usaremos o dataset **Penguins**, fornecido pela biblioteca `seaborn`. Ele contém informações sobre três espécies de pinguins coletadas nas Ilhas Palmer.

### 📜 Descrição das Colunas:
- **species**: Espécie do pinguim (*Adelie, Chinstrap, Gentoo*)
- **island**: Ilha onde o pinguim foi encontrado (*Biscoe, Dream, Torgersen*)
- **bill_length_mm**: Comprimento do bico em milímetros
- **bill_depth_mm**: Profundidade do bico em milímetros
- **flipper_length_mm**: Comprimento da nadadeira em milímetros
- **body_mass_g**: Massa corporal do pinguim em gramas
- **sex**: Sexo do pinguim (*Male, Female*)

## 📥 Importando Bibliotecas

In [1]:
import pandas as pd  # Biblioteca para manipulação de dados
import seaborn as sns  # Biblioteca para carregar o dataset
import os # Biblioteca padrão do Python para funções básicas do sistema operacional (arquivos, pastas, caminhos, variáveis de ambiente)

# A partir de agora vamos nos referir ao pandas apenas como pd e ao seaborn apenas como sns

## 📂 Carregando e Explorando o Dataset

In [2]:

# Carregar o dataset 'penguins' do seaborn
df = sns.load_dataset('penguins')

# Exibir as primeiras 10 linhas da tabela para conhecer os dados
df.head(10)  # Mostra as 10 primeiras linhas da tabela para análise inicial

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

## 📊 Informações Básicas da Tabela

In [3]:

# Verificar as colunas disponíveis e seus tipos de dados
df.info()  # Mostra a estrutura do DataFrame, tipos de dados e valores nulos

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [4]:

# Verificar se há valores ausentes no dataset
df.isnull().sum()  # Retorna a quantidade de valores nulos por coluna

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [5]:

# Resumo estatístico das colunas numéricas
df.describe()  # Mostra estatísticas descritivas como média, desvio padrão e quartis
#Além disso, é bom também para encontrar outliers
#As outras colunas como são categóricas, não saíram. Por óbvio só as que são numéricas com decimal (float64) aparecem

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

## 📝 Renomeando Colunas

In [6]:
#Renomeando algumas colunas
df = df.rename(columns={'species': 'especie', 'body_mass_g': 'massa_corporal_g','island':'ilha','sex':'sexo','flipper_length_mm':'nadadeira_mm'})

In [7]:

# Exibir os novos nomes das colunas após a alteração
df.columns  # Lista todas as colunas do DataFrame

Index(['especie', 'ilha', 'bill_length_mm', 'bill_depth_mm', 'nadadeira_mm',
       'massa_corporal_g', 'sexo'],
      dtype='str')

## 🔍 Selecionando Linhas e Colunas

In [8]:
# Selecionar apenas algumas colunas relevantes para análise
df_subset = df[['especie', 'ilha', 'massa_corporal_g','sexo','nadadeira_mm']]
#Aqui mudei de df para df_subset, porque se tiver que refazer algo, eu não preciso rodar o código inteiro novamente

In [9]:
# Exibir as primeiras linhas da tabela reduzida
df_subset.head()  # Mostra as 5 primeiras linhas do subconjunto criado

  especie       ilha  massa_corporal_g    sexo  nadadeira_mm
0  Adelie  Torgersen            3750.0    Male         181.0
1  Adelie  Torgersen            3800.0  Female         186.0
2  Adelie  Torgersen            3250.0  Female         195.0
3  Adelie  Torgersen               NaN     NaN           NaN
4  Adelie  Torgersen            3450.0  Female         193.0

In [10]:
#Vamos transformar os valores da massa dos pinguins de gramas para quilos

df_subset.iloc[:,2]=df_subset.iloc[:,2]/1000 #iloc = index location
df_subset.head()

  especie       ilha  massa_corporal_g    sexo  nadadeira_mm
0  Adelie  Torgersen              3.75    Male         181.0
1  Adelie  Torgersen              3.80  Female         186.0
2  Adelie  Torgersen              3.25  Female         195.0
3  Adelie  Torgersen               NaN     NaN           NaN
4  Adelie  Torgersen              3.45  Female         193.0

In [11]:
#Agora vamos renomear novamente a coluna de g para kg

df_subset = df_subset.rename(columns={'massa_corporal_g': 'massa_corporal_kg'})
df_subset.head()

  especie       ilha  massa_corporal_kg    sexo  nadadeira_mm
0  Adelie  Torgersen               3.75    Male         181.0
1  Adelie  Torgersen               3.80  Female         186.0
2  Adelie  Torgersen               3.25  Female         195.0
3  Adelie  Torgersen                NaN     NaN           NaN
4  Adelie  Torgersen               3.45  Female         193.0

## 🗑️ Removendo Colunas e Linhas

In [12]:

#Digamos que mudamos de ideia e nadadeiras não é mais importante
# Apagar a quinta coluna (índice 4) do dataset original
df_subset.pop(df_subset.columns[4])

df_subset.head()

  especie       ilha  massa_corporal_kg    sexo
0  Adelie  Torgersen               3.75    Male
1  Adelie  Torgersen               3.80  Female
2  Adelie  Torgersen               3.25  Female
3  Adelie  Torgersen                NaN     NaN
4  Adelie  Torgersen               3.45  Female

In [13]:
#Digamos que por algum motivo eu não quero a quarta linha (índice 3) também
df_subset.drop(index=3, inplace=True)  # Remove a linha de índice 3 diretamente no df_subset, sem precisar criar uma nova variável
df_subset.head()

  especie       ilha  massa_corporal_kg    sexo
0  Adelie  Torgersen               3.75    Male
1  Adelie  Torgersen               3.80  Female
2  Adelie  Torgersen               3.25  Female
4  Adelie  Torgersen               3.45  Female
5  Adelie  Torgersen               3.65    Male

In [14]:
#Onde está o valor nulo da coluna massa_corporal_kg?

df_subset[df_subset["massa_corporal_kg"].isnull()]

    especie    ilha  massa_corporal_kg sexo
339  Gentoo  Biscoe                NaN  NaN

## 🔄 Lidando com Valores Nulos

In [15]:
# 📌 Preencher valores nulos da coluna 'massa_corporal_kg' com a média da própria coluna

df_subset['massa_corporal_kg'] = df_subset['massa_corporal_kg'].fillna(
    df_subset['massa_corporal_kg'].mean()  # Calculamos a média da coluna 'massa_corporal_kg' para substituir os valores nulos
)  # O método fillna() retorna uma nova Series com os NaNs preenchidos, e essa nova versão é salva na coluna original

# 📌 Exibir as primeiras linhas para confirmar que os valores nulos foram preenchidos corretamente
df_subset.loc[339]  # acessa a linha cujo índice é 339
#Atenção, 339 não quer dizer que é 339º, quer dizer que o índice tem o "nome" de 339

especie                Gentoo
ilha                   Biscoe
massa_corporal_kg    4.201754
sexo                      NaN
Name: 339, dtype: object

In [16]:
#Vamos ver se ainda temos valores nulos
df_subset.info()

<class 'pandas.DataFrame'>
Index: 343 entries, 0 to 343
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   especie            343 non-null    str
 1   ilha               343 non-null    str
 2   massa_corporal_kg  343 non-null    float64
 3   sexo               333 non-null    str
dtypes: float64(1), str(3)
memory usage: 21.5 KB

In [17]:
#Poderíamos retirar a coluna sexo, mas digamos que ela é importante para nossa análise
#Como é uma variável categórica, não é possível plotarmos valores nulos, então vamos simplesmente apagá-los
# Remover linhas que ainda contenham valores nulos
df_subset.dropna(inplace=True)  # Exclui qualquer linha que ainda tenha valores nulos
df_subset.info()

<class 'pandas.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   especie            333 non-null    str
 1   ilha               333 non-null    str
 2   massa_corporal_kg  333 non-null    float64
 3   sexo               333 non-null    str
dtypes: float64(1), str(3)
memory usage: 13.0 KB

In [18]:
# Verificar novamente se há valores nulos
df_subset.isnull().sum()  # Confirma que não há mais valores ausentes no dataset

especie              0
ilha                 0
massa_corporal_kg    0
sexo                 0
dtype: int64

## 🔢 Criando Novas Colunas

In [19]:

# Criar uma nova coluna 'leve', que indica se o pinguim é mais leve que 4kg
df_subset['É leve?'] = df_subset['massa_corporal_kg'] < 4  # Retorna True para pinguins abaixo da média

In [20]:

# Exibir as primeiras linhas para visualizar a nova coluna
df_subset.head()  # Confere a adição da nova coluna ao DataFrame

  especie       ilha  massa_corporal_kg    sexo  É leve?
0  Adelie  Torgersen               3.75    Male     True
1  Adelie  Torgersen               3.80  Female     True
2  Adelie  Torgersen               3.25  Female     True
4  Adelie  Torgersen               3.45  Female     True
5  Adelie  Torgersen               3.65    Male     True

In [21]:
#Como provavelmente está em ordem crescente, vamos ver os últimos 10 valores e checar se a parte "pesado" está como falso
df_subset.tail(10)

    especie    ilha  massa_corporal_kg    sexo  É leve?
332  Gentoo  Biscoe              4.650  Female    False
333  Gentoo  Biscoe              5.500    Male    False
334  Gentoo  Biscoe              4.375  Female    False
335  Gentoo  Biscoe              5.850    Male    False
337  Gentoo  Biscoe              6.000    Male    False
338  Gentoo  Biscoe              4.925  Female    False
340  Gentoo  Biscoe              4.850  Female    False
341  Gentoo  Biscoe              5.750    Male    False
342  Gentoo  Biscoe              5.200  Female    False
343  Gentoo  Biscoe              5.400    Male    False

In [22]:
#Não gostei do true ou false, vamos substituir por sim ou não e também traduzir os sexos
df_subset['É leve?'] = df_subset['É leve?'].replace({True: 'Sim', False: 'Não'})
df_subset['sexo'] = df_subset['sexo'].replace({"Female": 'Fêmea', "Male": 'Macho'})
df_subset.head()

  especie       ilha  massa_corporal_kg   sexo É leve?
0  Adelie  Torgersen               3.75  Macho     Sim
1  Adelie  Torgersen               3.80  Fêmea     Sim
2  Adelie  Torgersen               3.25  Fêmea     Sim
4  Adelie  Torgersen               3.45  Fêmea     Sim
5  Adelie  Torgersen               3.65  Macho     Sim

## 💾 Salvando a Tabela Modificada

In [24]:
df_subset.to_excel("pinguins.xlsx", index=False)  # Salva o arquivo sem o índice

# from google.colab import files
# files.download("pinguins.xlsx")  # Faz o download do arquivo